### ISSUE TITLE
NoReverseMatch error with Django 1.9 on /admin/iprestrict/rule/ page

### ISSUE THREAD

**Issue by roman-oxenuk** [muccg/django-iprestrict#15]
In Django 1.9 I get a NoReverseMatch error when I try to open an admin page with list of all rules (url: /admin/iprestrict/rule/)

As I understand, Django 1.9 creates url namespace when you [specify] (https://github.com/muccg/django-iprestrict/blob/master/iprestrict/urls.py#L5) app_name in your urls.py
So, because of that, django reverse function is not able to do reverse [here] (https://github.com/muccg/django-iprestrict/blob/master/iprestrict/models.py#L144) and [here] (https://github.com/muccg/django-iprestrict/blob/master/iprestrict/models.py#L150)

**Comment by roman-oxenuk** [comment]
#16

**Comment by sztamas** [comment]
Hi, thanks for raising the issue and for the PR.
I ended up using a slightly different implementation, that also works on Django 1.7.
I also found another related issue on the iprestrict test page. I will fix that as well in the next release.

**Comment by sztamas** [comment]
This is still a problem in Django 1.9.
@roman-oxenuk you were right about Django 1.9 creating a namespace for the app.
The PR doesn't apply anymore, but I will add a fix that uses the namespace.
Credit to @roman-oxenuk.
The fix would break pre 1.9 setups, so updating the docs to specify the namespace when including urls.
