### ISSUE TITLE
Add support for IPv6

### ISSUE THREAD

**Issue by liquidfire228** [muccg/django-iprestrict#26]
`invalid literal for int() with base 10: '[IPV6 Address]'`

The error is occurring in iprestrict/ip_utils.py, in the to_number function.

I should note I have a proxy in my way which sends everything in as 127.0.0.1, I have to rely on the x-forwarded-for header, thus I have IPRESTRICT_TRUSTED_PROXIES = ['127.0.0.1'] in my settings.py.

**Comment by sztamas** [comment]
Yes, you are right IPv6 support has been on the TODO list for quite some time now.

Will see when I will have some time to implement it...

**Comment by sztamas** [comment]
IPv6 support available in the just released 1.2.0 version.
