### ISSUE TITLE
Templates and static files not included in pip package

### ISSUE THREAD

**Issue by bctiemann** [muccg/django-iprestrict#27]
I've installed the package via PyPI ("pip install django-iprestrict"), and the templates directory does not appear to be in the archive. I can't use the configuration page without manually downloading test_rules.html and putting it manually into another template dir.

**Comment by bctiemann** [comment]
Same is true of the static directory. I have to manually collect all the js and css files.

**Comment by sztamas** [comment]
Thanks for reporting the problem and sorry for the inconvenience.

I created and uploaded version 1.1.1 to PyPI that has the templates and static files included.

**Comment by bctiemann** [comment]
Awesome. Thanks very much for the quick response!

Brian
