### ISSUE TITLE
Could not add the Country code given in the example 

### ISSUE THREAD

**Issue by sagarg1988** [muccg/django-iprestrict#29]
Gives the error when trying to add the country code in the locationbasedipgroup  through admin .

**Comment by sagarg1988** [comment]
Error like must be valid country code

**Comment by sztamas** [comment]
Can you please paste in the exact validation message you're getting?
It should contain only the country codes that it doesn't consider valid so that might give a better indication of what's going on.

**Comment by sagarg1988** [comment]
XX  must be a valid country code
  This is the error I  came across , Actually when validating  the country from json files is having the issue. Look at it .

**Comment by sztamas** [comment]
That validation message should have quotes around the country code. 
Can you please paste it in including the quotes? That "XX" might be "XX " instead (note the extra space at the end).

Sorry, I don't understand what you mean by the json files.

What are you trying to do when you get the error? 
Can you describe you're actions in more detail?
What do you expect to happen and what happens instead?

**Comment by sztamas** [comment]
OK, so `pycountry` changed the code name in a backward incompatible way from `alpha2` to `alpha_2` in _16.10.23rc1_ (2016-10-23)_.

`setup.py` specifies `pycountry 1.20` as a requirement, so if the package is installed using `setup.py` everything should work as expected.

I'm happy to switch to the newer version of `pycountry`, but that's a separate issue.

**Comment by sztamas** [comment]
Reference: https://github.com/muccg/django-iprestrict/issues/31
