### ISSUE TITLE
Cannot programmatically create new IPGroup object.

### ISSUE THREAD

**Issue by objectivemorality** [muccg/django-iprestrict#33]
`IPGroup.objects.create(name='test',type='range')` 

gives the error: 

`IntegrityError: null value in column "type" violates not-null constraint
DETAIL:  Failing row contains (10, test, null, null).`

Hint: line 49 in models.py

**Comment by sztamas** [comment]
Sorry, for the late response.
Can you please create the row using the specific subclasses of `IPGroup`, namely `RangeBasedIPGroup` or `LocationBasedIPGroup`.

For your example:

`RangeBasedIPGroup.objects.create(name='test')`

**Comment by sztamas** [comment]
Fixed by https://github.com/muccg/django-iprestrict/releases/tag/1.3.1.
