### ISSUE TITLE
migration ran successfully, but initial data is missing

### ISSUE THREAD

**Issue by bravamin** [muccg/django-iprestrict#34]
I followed the steps to install and ran the migration successfully.  However, I don't see any initial data. Am I missing a step somewhere?
```
  Applying iprestrict.0001_initial... OK
  Applying iprestrict.0002_initial_data... OK
  Applying iprestrict.0003_add_ipgroup_types... OK
  Applying iprestrict.0004_add_iplocation... OK
  Applying iprestrict.0005_add_reverse_ipgroup... OK
  Applying iprestrict.0006_auto_20161013_1327... OK
```

**Comment by sztamas** [comment]
Hi, sorry for the late response.

I've just run the migrations and I do see the initial rules in the database.
What do you mean by not seeing the initial data.

What do you expect to see and what do you see?

**Comment by sztamas** [comment]
Closing old issue.
Please re-open if still a problem.
