### ISSUE TITLE
possible to deny you way out of admin 

### ISSUE THREAD

**Issue by breslover** [muccg/django-iprestrict#35]
please allow access to the admin url just in case you block your own super-user ip address when testing or otherwise.

**Comment by sztamas** [comment]
You can add an ALLOW rule for all URLs that start with `admin/` to accomplish that.

You have to be careful not to lock yourself out. You should [test](http://django-iprestrict.readthedocs.io/en/latest/configuration.html#testing-the-rules) your setup before enabling it.

If you manage to still lock your self out, you can still edit the rules by using a Django shell, or just disable the `IPRestrictMiddleware` temporarily and use admin to fix your mistake.
