### ISSUE TITLE
Add note to installation docs about IPRESTRICT_GEOIP_ENABLED

### ISSUE THREAD

**Issue by caduri** [muccg/django-iprestrict#37]
The docs mention pycountry package is not mandatory 
but when django try to import iprestrict in models you added this line 
`from .geoip import get_geoip, NO_COUNTRY`
and geoip require pycountry

**Comment by caduri** [comment]
geoip2 is also required

**Comment by caduri** [comment]
I found this setting IPRESTRICT_GEOIP_ENABLED that I needed to set to False for it to work

The real issue is with the docs that doesn't state that I must set it to false

**Comment by sztamas** [comment]
The docs do mention `IPRESTRICT_GEOIP_ENABLED` in 2 places, but not in the installation part.
Adding a note to the installation part about it.
