### ISSUE TITLE
Cannot access iprestrict url to test the rules

### ISSUE THREAD

**Issue by caduri** [muccg/django-iprestrict#38]
When I install the package using pip, it doesn't install the templates and static dirs

**Comment by sztamas** [comment]
Sorry for that, don't know what happened with the package.
Please install latest package `1.3.2` that has the files.

**Comment by caduri** [comment]
Thanks!

**Comment by hellvix** [comment]
1.4 has a similar problem. If you try to test a rule, accessing `/iprestrict` you get:

```
TemplateDoesNotExist at /iprestrict/
iprestrict/test_rules.html
```

Django 1.11.3
