### ISSUE TITLE
Trusting ALL Proxies?

### ISSUE THREAD

**Issue by MetricMike** [muccg/django-iprestrict#39]
When using managed proxies/load balancers (such as on AWS), I'm explicitly warned against assuming IP addresses since they can change at any time. This presents a problem when trying to get the client IP with IPRESTRICT_TRUSTED_PROXIES.

I think one solution would be adding a boolean IPRESTRICT_TRUST_ALL_PROXIES setting that skips the check on https://github.com/muccg/django-iprestrict/blob/master/iprestrict/middleware.py#L54.

Would you be open to a pull request with that change and a supporting test?

**Comment by sztamas** [comment]
Sorry for the very late reply, but I was on leave and the GitHub notification email got lost somehow in my mailbox.

Isn't the already existing `IPRESTRICT_IGNORE_PROXY_HEADER` setting doing exactly what you want?

https://github.com/muccg/django-iprestrict/blob/master/iprestrict/middleware.py#L47

**Comment by MetricMike** [comment]
No worries - open source is free so it's unreasonable to demand your attention. I did go ahead and [fork](https://github.com/MetricMike/django-iprestrict/tree/feature/allow-proxies) so I could have the flag available for another project, but I still think this is generally useful.

`IPRESTRICT_IGNORE_PROXY_HEADER` assumes that `REMOTE_ADDR` is the IP address of the client, but for apps on [AWS](http://docs.aws.amazon.com/elasticloadbalancing/latest/classic/x-forwarded-headers.html#x-forwarded-for), [GCP](https://cloud.google.com/compute/docs/load-balancing/http/#components), or [Azure](https://docs.microsoft.com/en-us/azure/application-gateway/application-gateway-faq) that have a load balancer, that's the IP address of the load balancer/proxy and the client's IP is `X-Forwarded-For`.

Since these apps (if configured so) can only receive traffic from those load balancers, I can assume that `X-Fowarded-For` has not been spoofed and can be trusted as if it were included in `IPRESTRICT_TRUSTED_PROXIES`.

**Comment by sztamas** [comment]
OK, I see what you mean now.

If you don't mind creating a PR I'm happy to include your change.

The only comment is that I would prefer doing the shortcutting just above the `for` statement instead of in the nested `if`.

More of a stylistic preference, keeps the `if` conditions shorter and my brain more idle :)

**Comment by MetricMike** [comment]
Thanks! :smile:

**Comment by sztamas** [comment]
Thanks for the contribution! ;-)
