### ISSUE TITLE
Cannot access iprestrict url to test

### ISSUE THREAD

**Issue by hellvix** [muccg/django-iprestrict#42]
1.4 has a similar problem to https://github.com/muccg/django-iprestrict/issues/38. If you try to test a rule, accessing `/iprestrict` you get:

```
TemplateDoesNotExist at /iprestrict/
iprestrict/test_rules.html
```

`/iprestrict/page` yields 404, whether the rule is active or not. So I don't think this is working.

Django 1.11.3 and 1.11.7.

**Comment by sztamas** [comment]
Sorry about that!

At least I figured out that the files aren't included when I'm making the distribution on Mac OS instead of Linux.

I've just released ``1.4.1`` that has the missing files.

Please re-open if there are any problems.
