### ISSUE TITLE
Admin mark_safe issue

### ISSUE THREAD

**Issue by eriktelepovsky** [muccg/django-iprestrict#46]
Hi. The "Move Up" and "Move Down" actions are not marked as safe using **mark_safe()** in Django admin:

![image](https://user-images.githubusercontent.com/2685808/41531886-3e399c1c-72f5-11e8-8ffd-4ccc472e10d0.png)

Using:
Django==2.0.6
django-iprestrict from repository

**Comment by sztamas** [comment]
@eriktelepovsky thanks for reporting it!

Fixed in https://github.com/muccg/django-iprestrict/releases/tag/1.5.1
