### ISSUE TITLE
IP range description

### ISSUE THREAD

**Issue by eriktelepovsky** [muccg/django-iprestrict#51]
Hi. Can you add description field into IPRange model, please? It would be helpful to have an option to add a note for specific IP addresses. Thank you.

**Comment by sztamas** [comment]
Hi, added the description field as requested.

Available in the 1.7.0 release: https://github.com/muccg/django-iprestrict/releases/tag/1.7.0

**Comment by eriktelepovsky** [comment]
Perfect! Thank you ;)
