### ISSUE TITLE
Error when running Selenium tests with IPRestrict

### ISSUE THREAD

**Issue by mradochonski** [muccg/django-iprestrict#7]
runserverselenium_1 | Traceback (most recent call last):
runserverselenium_1 |   File "/env/lib/python2.7/site-packages/django/contrib/staticfiles/handlers.py", line 63, in __call__
runserverselenium_1 |     return self.application(environ, start_response)
runserverselenium_1 |   File "/env/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 189, in __call__
runserverselenium_1 |     response = self.get_response(request)
runserverselenium_1 |   File "/env/lib/python2.7/site-packages/django/core/handlers/base.py", line 184, in get_response
runserverselenium_1 |     response = self.get_exception_response(request, resolver, 403)
runserverselenium_1 |   File "/env/lib/python2.7/site-packages/django/core/handlers/base.py", line 90, in get_exception_response
runserverselenium_1 |     response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
runserverselenium_1 |   File "/env/lib/python2.7/site-packages/django/core/handlers/base.py", line 261, in handle_uncaught_exception
runserverselenium_1 |     return debug.technical_500_response(request, *exc_info)
runserverselenium_1 |   File "/env/lib/python2.7/site-packages/django_extensions/management/technical_response.py", line 5, in null_technical_500_response
runserverselenium_1 |     six.reraise(exc_type, exc_value, tb)
runserverselenium_1 |   File "/env/lib/python2.7/site-packages/django/core/handlers/base.py", line 87, in get_exception_response
runserverselenium_1 |     response = callback(request, **param_dict)
runserverselenium_1 |   File "/env/lib/python2.7/site-packages/django/utils/decorators.py", line 110, in _wrapped_view
runserverselenium_1 |     response = view_func(request, *args, **kwargs)
runserverselenium_1 |   File "/env/lib/python2.7/site-packages/django/views/defaults.py", line 81, in permission_denied
runserverselenium_1 |     return http.HttpResponseForbidden(template.render(request=request))
runserverselenium_1 |   File "/env/lib/python2.7/site-packages/django/template/backends/django.py", line 74, in render
runserverselenium_1 |     return self.template.render(context)
runserverselenium_1 |   File "/env/lib/python2.7/site-packages/django/template/base.py", line 209, in render
runserverselenium_1 |     with context.bind_template(self):
runserverselenium_1 |   File "/usr/local/lib/python2.7/contextlib.py", line 17, in __enter__
runserverselenium_1 |     return self.gen.next()
runserverselenium_1 |   File "/env/lib/python2.7/site-packages/django/template/context.py", line 241, in bind_template
runserverselenium_1 |     updates.update(processor(self.request))
runserverselenium_1 |   File "/app/rdrf/rdrf/user_context.py", line 5, in is_admin
runserverselenium_1 |     user = request.user
runserverselenium_1 | AttributeError: 'WSGIRequest' object has no attribute 'user'

iprestrict is added to middlewares in settings.py, I suspect that the order matters?

**Comment by rvl** [comment]
Yep, the order matters (see [docs](http://django-iprestrict.readthedocs.org/en/latest/configuration.html#enabling-the-middleware)).

This particular error seems to be due to the value of `settings.TEMPLATE_CONTEXT_PROCESSORS`. The `rdrf.user_context.is_admin` function needs to consider that it might be called without all middlewares having been run, i.e. the `AuthenticationMiddleware` may not have added the `user` attribute yet.

Possibly, if `IPRestrictMiddleware` is added after `CommonMiddleware` and before everything else, there won't be a 500 error at all.

**Comment by rvl** [comment]
I assume this is working now @mradochonski ?
