### ISSUE TITLE
Migrations not included in release on pypi

### ISSUE THREAD

**Issue by nanorepublica** [muccg/django-iprestrict#9]
Doesn't give the greatest confidence, especially when the middleware is active then all access is denied without any rules being present.

**Comment by rvl** [comment]
Thanks for catching that, @nanorepublica. It happened since I moved from South to Django migrations. We haven't been using the initial data provided by the migrations, so never noticed. Release [0.4.2](https://github.com/muccg/django-iprestrict/releases/tag/0.4.2) with migrations is on PyPI now.
